app:
  redis:
    host: localhost
    port: 6379

    consumer:
      groupName: app
      destination: queueName
      offset: 0-0
  metrics:
    project: example-queue
    service: example-queue-local

management:
  endpoints:
    web.exposure.include: health,metrics
  metrics:
    export:
      graphite:
        enabled: true
        host: mon.finch.fm
        protocol: plaintext
        tags-as-prefix: project
        port: 2003
        step: 1s